### PR TITLE
Implement new design for mobile responsive sidebar on Map page

### PR DESCRIPTION
**Pull request by maurizi**
Reworks the UI for adding trees, viewing and editing trees, and viewing ecobenefits.
Also fixes a few minor bugs, and adds autoprefixer to our webpack config for better cross-browser support.

The one UI change made to the desktop version of the site is that I added a loading indicator for ecobenefits on page load.

Connects to #2865 
Connects to #2677 
Connects to #2683

### CODE REVIEW

**Comment by lederer** [comment]
In Mobile Safari, the browser's bottom nav bar occludes the app's bottom panel.

For reference, here's the bottom of the Add Tree page in a narrow desktop window:

screen shot 2016-11-21 at 2 15 26 pm

And here it is in Mobile Safari:

img_0487

You can see the bottom panel with Next/Prev buttons and "Step 1 of 3" is hiding rather undiscoverably.


Similarly, here's the main map view, with Eco Bens occluded:

img_0488

**Comment by lederer** [comment]
When adding a tree, after setting the location via the map, the blue Search button feels like the natural call to action. My first thought was, I wonder why that button says "Search" instead of, say, "Next" or similar. I guess I'll just press it anyway, and I did. I literally overlooked the actual "Next" button only a few pixels away.

Further, after pressing Search, a mysterious menu appears off of the address field. It's impossible to scroll it into view.

screen shot 2016-11-21 at 2 15 38 pm

Suggestion:
Hide the Search btn completely if it's irrelevant. Else, demote it visually (eg, make it white instead of blue. Make the Next button stand out like a CTA (blue?).

**Comment by lederer** [comment]
When a non-tree resource is selected, eg a Rain Barrel, the "Resource / Rain Barrel" labels are misaligned with the "Rain Barrel / Nearby Address: / 763 E Hilton…" labels. They should all be aligned.

screen shot 2016-11-21 at 2 29 05 pm

**Comment by lederer** [comment]
On the login screen, the Register button needs additional `margin-top`:
screen shot 2016-11-21 at 2 18 24 pm

**Comment by lederer** [comment]
The iOS 10 page zooming workaround doesn't appear to be working. 

On my iPhone 7 / iOS 10 / Mobile Safari, I can still pinch (non-map components) to zoom the page. 

Double-tapping seems to have no effect though (ie, is working correctly).

**Comment by lederer** [comment]
This isn't limited to narrow widths, but appears to be a recent change. Is it part of this PR?

The Tree Care dropdowns in Advanced Search have both dropdown arrows AND rocker arrows:

screen shot 2016-11-21 at 2 56 19 pm

**Comment by maurizi** [comment]
> In Mobile Safari, the browser's bottom nav bar occludes the app's bottom panel.

This took a bit of research, but I eventually got this in much better shape using [viewport-units-buggyfill](https://github.com/rodneyrehm/viewport-units-buggyfill). That does mean you can't see ecobenefits until JS loads, but I couldn't find a better solution.

> When adding a tree, after setting the location via the map, the blue Search button feels like the natural call to action. My first thought was, I wonder why that button says "Search" instead of, say, "Next" or similar. I guess I'll just press it anyway, and I did. I literally overlooked the actual "Next" button only a few pixels away.

> Further, after pressing Search, a mysterious menu appears off of the address field. It's impossible to scroll it into view.

I fixed the popup to open above instead of below the field, and I changed the search button to a more neutral gray, and gave the Next / Prev buttons some color:
localhost-6060-mike-us-map--z 18-40 02137--75 20621 m addtree iphone 5

> When a non-tree resource is selected, eg a Rain Barrel, the "Resource / Rain Barrel" labels are misaligned with the "Rain Barrel / Nearby Address: / 763 E Hilton…" labels. They should all be aligned.

Fixed this.

> On the login screen, the Register button needs additional margin-top, and is off-center horizontally (compare to Login btn above it):

This wasn't introduced in this PR. I added a issue https://github.com/OpenTreeMap/otm-core/issues/2869 for fixing it

> The iOS 10 page zooming workaround doesn't appear to be working.

I removed this until we can come up with a better workaround.

> The Tree Care dropdowns in Advanced Search have both dropdown arrows AND rocker arrows:

I can't reproduce this. What browser is this on?

**Comment by RickMohr** [comment]
Regression -- the "Next" button used to be gray but is now colored:
image

**Comment by maurizi** [comment]
> Regression -- the "Next" button used to be gray but is now colored:

This isn't a regression, I did this on @lederer's advice

**Comment by RickMohr** [comment]
Intentional change? Add tree "Search" button is now gray and right-aligned instead of colored and next to the input box.

Was:
image

Now:
image

**Comment by RickMohr** [comment]
Regression - Add tree search results no longer attached to input box. Should be:
image
But is now attached to the map. (Desktop mode)

**Comment by RickMohr** [comment]
Regression (desktop width):
1) Add a Bioswale
2) In step 4, type text instead of a number
3) Continue and click "Done"

Expected: error message shown, and incorrect value remains in input box
Actual: no error message shown, and incorrect value is cleared

**Comment by RickMohr** [comment]
Regarding changing the color of the "Next" button, I suggest making it a separate "Design" issue rather than piggybacking on this PR. Issues:
1) There is no longer a visual distinction between disabled and enabled
2) The fill color is still gray when you hover, which looks odd to me and may not work with all custom colors
3) We don't have unfilled colored buttons anywhere else in the UI, and it looks odd to me.

**Comment by RickMohr** [comment]
I think adding a "Loading Ecobenefits" spinner should be a separate PR. Issues:
* It's big and draws your attention, which I don't think we want. I'd prefer something less obtrusive. (Maybe a smaller spinner on the "Eco Benefits" header bar?)
* It looks odd to see it flash on load. Might be better to only show it if it hasn't appeared after a 1 or 2 seconds.
* Spinner and message shown forever if call times out.

**Comment by RickMohr** [comment]
Mobile: clicking gear icon adds extraneous scrollbars
image

**Comment by RickMohr** [comment]
Mobile: gear menu doesn't show above expanded ecobenefits panel

**Comment by RickMohr** [comment]
Mobile: expanded ecobenefit panel is one pixel too tall? The green underline is slightly cut off:
image
image

**Comment by RickMohr** [comment]
Mobile: Select a tree and click the bottom header -- scrollbar shown temporarily as bottom header is sliding up. (Or two scrollbars if you've selected a tree with ecobenefits.)

**Comment by RickMohr** [comment]
Mobile: Select a tree toward the bottom of the map and click the footer -- tree is not visible on map and you can't pan the map!

**Comment by lederer** [comment]
@maurizi The duplicate dropdown arrows in Advanced Search > Tree Care were in Chrome 54/Mac.

**Comment by RickMohr** [comment]
Gap in diameter fields:
image

**Comment by RickMohr** [comment]
The gray of the step header is very similar to the gray of the map -- consider making them easier to distinguish.
image

**Comment by RickMohr** [comment]
These menu items have different top/bottom spacing. Can they both be centered vertically?
image

**Comment by RickMohr** [comment]
Above comments notwithstanding, nice design and very usable!

**Comment by maurizi** [comment]
@RickMohr @lederer This is ready for another look.

> Intentional change? Add tree "Search" button is now gray and right-aligned instead of colored and next to the input box.

Fixed in https://github.com/OpenTreeMap/otm-core/pull/2867/commits/89b3aea39ed356fa36decbaea4d3c153fcd5c0a5

> Regression -- the "Next" button used to be gray but is now colored:

Fixed in https://github.com/OpenTreeMap/otm-core/pull/2867/commits/86bc21e148f68ec26bfbe1c36c5f184fce0ace31. For simplicity this continues to have the same style on desktop and mobile.

> Regression - Add tree search results no longer attached to input box. Should be:

Fixed in https://github.com/OpenTreeMap/otm-core/pull/2867/commits/2fb2c0350700b68314f5f682a8fd5218a7dc9726

> Regression (desktop width):
> 
> Add a Bioswale
> In step 4, type text instead of a number
> Continue and click "Done"
> Expected: error message shown, and incorrect value remains in input box
> Actual: no error message shown, and incorrect value is cleared

I can't reproduce this anymore.

> I think adding a "Loading Ecobenefits" spinner should be a separate PR. Issues:
> 
> It's big and draws your attention, which I don't think we want. I'd prefer something less obtrusive. (Maybe a smaller spinner on the "Eco Benefits" header bar?)
> It looks odd to see it flash on load. Might be better to only show it if it hasn't appeared after 1 or 2 seconds.
> Spinner and message shown forever if call times out.
> The counts above the map also don't appear immediately -- do they need a spinner too?
> It's great to have some progress on this, but IMO we want to get it right and not distract from the responsive issues.

I changed this in https://github.com/OpenTreeMap/otm-core/pull/2867/commits/27ac5dd5f699dbf1d6863f1bb38a91ebf85b6883
I talked to @lederer about this, and what we came up with was to keep the loading ecobenefits text in place (even on desktop), but with a more muted style and without the spinner.  We should definitely revisit this again soon though.

> Mobile: clicking gear icon adds extraneous scrollbars

> Mobile: gear menu and plus menu don't show above expanded ecobenefits panel

Fixed both of these in https://github.com/OpenTreeMap/otm-core/pull/2867/commits/057194e034ae41bf383313d5c77a77121ad8a9a6

> Mobile: expanded ecobenefit panel is one pixel too tall? The green underline is slightly cut off:

Good eye! Fixed this in https://github.com/OpenTreeMap/otm-core/pull/2867/commits/9105a82f1bf9a02ed305c8858482d7a8e193cd2e

> Mobile: Select a tree and click the footer -- scrollbar shown temporarily as bottom header is sliding up. (Or two scrollbars if you've selected a tree with ecobenefits.)

I decided to let this be, since mobile phones don't generally show scrollbars

> Mobile: Select a tree toward the bottom of the map and click the footer -- tree is not visible on map and you can't pan the map! Also can't move the tree.

This was tricky! Fixed in https://github.com/OpenTreeMap/otm-core/pull/2867/commits/d58b7df9f4b7e447de689e0a2a44ba337a7aa082 by panning the map to center on the selected feature when expanding the tree detail section on mobile, and panning back when closing it.

> @maurizi The duplicate dropdown arrows in Advanced Search > Tree Care were in Chrome 54/Mac.

Fixed in https://github.com/OpenTreeMap/otm-core/pull/2867/commits/d4185b036fd42ea69d863e71d8d96d7401b365c3

> The gray of the step header is very similar to the gray of the map -- consider making them easier to distinguish.

Fixed in https://github.com/OpenTreeMap/otm-core/pull/2867/commits/e6452c68683a71702ed1c7b3d4e234daa1769a04.  These headers now share the same styling as the selected tree header (on mobile only).

> These menu items have different top/bottom spacing. Can they both be centered vertically?

This is the Bootstrap default, and wasn't introduced by this PR, so I left it as-is.

**Comment by RickMohr** [comment]
Top menu items not aligned if green infrastructure not enabled:
image

**Comment by RickMohr** [comment]
Too much vertical space:
image

Not there on desktop:
image

**Comment by RickMohr** [comment]
All else looks good!

**Comment by RickMohr** [comment]
I'm still uncomfortable with changing the location of the "X" to exit "Add Tree" in desktop mode. The old way seems clearer to me:
image

Than the new way, which looks like you're closing a step rather than a mode:
image

**Comment by maurizi** [comment]
@RickMohr I addressed your comments:

> Top menu items not aligned if green infrastructure not enabled:

Fixed in https://github.com/OpenTreeMap/otm-core/pull/2867/commits/79a43255fb6142bbed4f9c52356e96b18eb4a4f6

> Too much vertical space:

Fixed in https://github.com/OpenTreeMap/otm-core/pull/2867/commits/10380f250666448b2e5f0af4407da3cfce456302

> I'm still uncomfortable with changing the location of the "X" to exit "Add Tree" in desktop mode. The old way seems clearer to me:

Fixed in https://github.com/OpenTreeMap/otm-core/pull/2867/commits/eff352abfcc4638cc52cd5f365a42efa88770510

@lederer I fixed the iOS scalable work-around (https://github.com/OpenTreeMap/otm-core/pull/2867/commits/30bd4f91883a196104696cc3fbf2e1e289e56da8), increased the size of the address search box (https://github.com/OpenTreeMap/otm-core/pull/2867/commits/e8fa02b159b555a3e7a06a6386507a2437aceb0c), and cleaned up typeaheads in add tree mode (https://github.com/OpenTreeMap/otm-core/pull/2867/commits/ef36cd97a98d12757f0c7c9021f9e1a73c889347) and (https://github.com/OpenTreeMap/otm-core/pull/2867/commits/0d86b1304512abfa7109539a5fe8e7b011c5ed87)

**Comment by RickMohr** [comment]
On my iPhone 6, clicking the address search box in "Add Tree" mode causes it to scroll off the top of the screen.

Other changes all look good.

**Pull request merged**
