### PR TITLE
Fix 500 when import started with no attachment

### PR DESCRIPTION
**Pull request by steventlamb**
connects #2459 on github

### CODE REVIEW

**Comment by RickMohr** [comment]
Consider simplifying this by putting the test before `process_csv` instead of inside it, and changing your test to call `start_import` and make its request with
```python
request = make_request({'type': tree})
```

**Comment by RickMohr** [comment]
+1 I didn't come up with a good way to test this, but I think the unit test is satisfactory.

**Comment by steventlamb** [comment]
I tested this by modifying the JS UI so that the import button is always available, and sent requests without an attachment. The `400` came back in the network tab with the appropriate message.

**Comment by RickMohr** [comment]
I'll try that.

**Comment by RickMohr** [comment]
I saw the 400 response with "No Attachment Received"

**Pull request merged**
