### PR TITLE
Remove unused provisioning items

### PR DESCRIPTION
**Pull request by maurizi**
Removes several provisioning items that will no longer be used.

### CODE REVIEW

**Comment by maurizi** [comment]
The testem JS tests aren't passing on Travis CI for some reason.  They _are_ passing on CircleCI, where they're being run in a slightly different way, which is curious.

**Comment by maurizi** [comment]
@jwalgran Commit messages have been updated

**Comment by jwalgran** [comment]
Those are some wonderfully helpful commit messages. Thanks.

**Comment by maurizi** [comment]
@jwalgran I updated our `.travis.yml` file to stop running the testem tests, since I couldn't figure out what caused them to fail.  They're still running on CircleCI, we're not losing code coverage in PR builds.

**Comment by jwalgran** [comment]
:+1:

**Comment by jwalgran** [comment]
It might be a good idea to hold off on merging this until after our next demo to avoid any CI complications

**Pull request merged**
