### PR TITLE
styles for embedded map

### PR DESCRIPTION
**Pull request by RobinIsTheBird**
# Style new embed page

* Place all radio buttons on the same line
* Only show width x height + Preview when Custom is checked
* Fix the width of the `iframe` input element
* Vertical spacing
* Fix responsive design
* Add `.hidden` class for error messages

--

Connects to OpenTreeMap/otm-addons#1232
Depends on OpenTreeMap/otm-addons#1240

### CODE REVIEW

**Comment by maurizi** [comment]
Looks good, the `embeddable` decorator is working well, and the styling looks good. :+1:

**Comment by RobinIsTheBird** [comment]
@azavea-bot reload

**Comment by RobinIsTheBird** [comment]
@azavea-bot rebuild

**Comment by RobinIsTheBird** [comment]
@tnation14 , adding you to the review because the changes in decorators and routes have to work in conjunction with OpenTreeMap/otm-cloud#279.

**Comment by maurizi** [comment]
:+1:

**Pull request merged**
