### PR TITLE
Add initial styling for new nested navigation on admin site

### PR DESCRIPTION
**Pull request by maurizi**

### CODE REVIEW

**Comment by jwalgran** [comment]
Looks good to me

**Comment by maurizi** [comment]
@ctaylo37 I think this is ready for you to build on top of.

**Comment by ctaylo37** [comment]
@maurizi sounds good.  I will probably start this tomorrow or Monday.

**Comment by maurizi** [comment]
@designmatty Do you think you can take a look at this, particularly https://github.com/OpenTreeMap/otm-core/commit/16134775fae5717fb1d95d9d261eca0da60c2b2e and let me know how it looks?  I'm not sure what the Azavea best practices are for writing SASS.

**Comment by maurizi** [comment]
Just realized @designmatty is in Maine...

**Comment by jwalgran** [comment]
:+1:

**Pull request merged**
