### PR TITLE
optimized spinners for both dark and light backgrounds

### PR DESCRIPTION
**Pull request by designmatty**
Should fix https://github.com/OpenTreeMap/otm-addons/issues/810

### CODE REVIEW

**Comment by designmatty** [comment]
This is just a suggestion @RickMohr but I think we should use an svg with a gif fallback instead of just using a gif. Let me know if this is something worth doing.

**Comment by maurizi** [comment]
The new spinners are _bigger_ than the ones they are replacing, and overflow their surrounding areas.  I think we need to have the new images match the size of the existing ones.

**Comment by designmatty** [comment]
I will fix this by the end of day friday.

**Comment by maurizi** [comment]
+1

**Pull request merged**
