### PR TITLE
Add RainGarden stewardship defaults

### PR DESCRIPTION
**Pull request by steventlamb**

### CODE REVIEW

**Comment by maurizi** [comment]
I think we have another case sensitivity issue going on.

I tried to save a stewardship action on a rain garden, and got the following issue:
```
Exception at /mike/features/3/
Malformed request - invalid field raingarden.udf:Stewardship
```

**Comment by RickMohr** [comment]
Looks like a good case for a unit test.

**Comment by steventlamb** [comment]
this is ready for another look

**Comment by jwalgran** [comment]
I added RainGarden to a newly created test map, saw the new stewardship choices, and was able to add a rain garden with stewardship and search for the specific stewardship type.

:+1:

**Pull request merged**
