### PR TITLE
Document input parameters for API endpoints

### PR DESCRIPTION
**Pull request by RickMohr**
Posting this for early feedback on the format.

### CODE REVIEW

**Comment by jwalgran** [comment]
I like the format.

For optional parameters, we should consider documenting the default value.

+1

**Comment by RickMohr** [comment]
@jwalgran, this is now ready for review.

**Comment by RickMohr** [comment]
Connects #2148

**Comment by jwalgran** [comment]
The stewardship UDF row under "Create a new plot and tree" has a "box" placeholder character when I view the rendered markdown in Github

screen shot 2015-07-16 at 8 44 03 am

**Comment by jwalgran** [comment]
+1

**Pull request merged**
