### PR TITLE
Fix broken comment moderation UI tests.

### PR DESCRIPTION
**Pull request by maurizi**

### CODE REVIEW

**Comment by jwalgran** [comment]
For reference, this is the failed test I see in latest build of the `develop` branch

```
======================================================================
FAIL: test_filtering (otm_comments.uitests.CommentReviewUITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/app/core/opentreemap/otm_comments/uitests.py", line 98, in test_filtering
    self.assert_num_rows(1, 'Only the hidden comment should be shown')
  File "/opt/app/core/opentreemap/otm_comments/uitests.py", line 58, in assert_num_rows
    self.assertEqual(num, len(rows), msg)
AssertionError: Only the hidden comment should be shown
```

**Comment by maurizi** [comment]
@azavea-bot rebuild

**Comment by jwalgran** [comment]
@azavea-bot rebuild

**Comment by jwalgran** [comment]
The UI tests pass on my machine and I verified that this does not affect the usability of buttons in the upper right of the comment moderation page.

👍

**Comment by RickMohr** [comment]
@maurizi, want to merge this so the build will work again?

**Pull request merged**
