### PR TITLE
Replace FreeNode IRC link with Gitter channel

### PR DESCRIPTION
**Pull request by maurizi**

### CODE REVIEW

**Comment by jwalgran** [comment]
This documentation leads me to believe that only members of the OpenTreeMap organization can use this room

https://gitter.zendesk.com/hc/en-us/articles/200178951-Gitter-rooms

I think we need to use ``opentreemap/otm-core`` as our public discussion room.

**Comment by dboyer** [comment]
Yes, I'd like this to be as public as possible.

**Comment by maurizi** [comment]
@jwalgran Updated to use `OpenTreeMap/otm-core` as the chat room.

**Comment by jwalgran** [comment]
+1

**Pull request merged**
