### PR TITLE
Users and Roles management pages

### PR DESCRIPTION
**Pull request by RickMohr**
Instance invitations
* New model `InstanceInvitation`
* Add `DEFAULT_FROM_EMAIL` to `default_settings.py`
* Email templates (`manage_treemap/templates/manage_treemap/emails`) use the generic term "tree map" rather than "OpenTreeMap".
* Notifications go to all users with management access, not just treemap owner (verified by unit tests)

Plugin functions:
* Add `user_is_instance_owner`
* Add `can_add_user`
* Remove `should_send_user_activation` (its functionality is now in `otm-core`)
* Remove duplicate definition of `get_viewable_instances_filter`

Also:
* Update email templates (`manage_treemap/templates/manage_treemap/emails`) to have generic text -- mostly replacing "OpenTreeMap" with "tree map".
* Add dependency to an old migration to fix a CircleCI crash

Required by OpenTreeMap/otm-addons#1497
Depends on OpenTreeMap/otm-cloud#366

### CODE REVIEW

**Comment by RickMohr** [comment]
@azavea-bot rebuild

**Comment by dboyer** [comment]
Is tree map sometimes one word and sometimes two words in the generic email templates? I'd prefer it as two words, if possible.

**Comment by RickMohr** [comment]
@dboyer, I've changed 2 occurrences of "treemap" to "tree map" in the email templates.

**Comment by RickMohr** [comment]
@azavea-bot rebuild

**Pull request merged**
