### PR TITLE
Make tile layers display above boundary polygon

### PR DESCRIPTION
**Pull request by RickMohr**
See discussion in code comments.

Connects #2569

### CODE REVIEW

**Comment by RickMohr** [comment]
@azavea-bot rebuild

**Comment by jwalgran** [comment]
On this branch the boundary layer is behind the ESRI basemap

screen shot 2016-05-17 at 1 32 28 pm

screen shot 2016-05-17 at 1 33 57 pm

**Comment by RickMohr** [comment]
The Google basemap's tiles are in a `div` separate from the tree dot tiles:
```html
<div class="leaflet-google-layer" ...> ... </div>
<div class="leaflet-map-pane" ...> ...tree dot tiles... </div>
<div class="leaflet-objects-pane" ...> ...boundary polygon... </div>
```
That allows us to put the boundary polygon between the basemap and the tree dot tiles.

But the ESRI basemap's tiles are in the same `div` as the tree dot tiles:
```html
<div class="leaflet-map-pane" ...> ...ESRI basemap tiles AND tree dot tiles... </div>
<div class="leaflet-objects-pane" ...> ...boundary polygon... </div>
```
Because the `leaflet-map-pane` has position absolute it establishes a separate stacking context and there's no way to put the boundary polygon and the tree dot tiles.

Since before too long we will likely switch to Leaflet 1.0 (which allows much finer control over the layer stacking order) and since ESRI basemaps aren't being used yet, I think we should address the issue when we switch to Leaflet 1.0. Entered as #2586.

**Comment by jwalgran** [comment]
👍

**Pull request merged**
