### PR TITLE
Fix quick edit move tree

### PR DESCRIPTION
**Pull request by RobinIsTheBird**
Check whether the plot is writable, not specific field.

--

Connects to #2870

### CODE REVIEW

**Comment by maurizi** [comment]
Code looks good to me (didn't test)

**Comment by jwalgran** [comment]
Is it possible to add to the commit message and explain why this is a good fix? Looking at just this diff without the broader scope of the permission system it may appear counterintuitive, since moving the plot only affects geometry field.

**Comment by RobinIsTheBird** [comment]
@jwalgran, I amended the commit message.

Git decided that my local branch was behind my fork branch. That's why there's a merge commit.

**Comment by maurizi** [comment]
:+1:

**Pull request merged**
