### PR TITLE
Show trees in bioswales on detail page

### PR DESCRIPTION
**Pull request by maurizi**
Also includes some general cleanups to the resource detail page.

Connects to #2161
Connects to #2122

### CODE REVIEW

**Comment by maurizi** [comment]
A bioswale with trees:
with-trees

A bioswale without trees:
no-trees

I used the same title we are currently using for the map popups as the text of the link.  I'm not sure if we need more information on the link beyond that.

**Comment by dboyer** [comment]
If possible, it would be useful to show the dbh next to the species since there may be multiple trees of the same species in the bioswale. If there's no dbh, we can just leave a blank or put "No diameter" - whatever's simpler.

**Comment by maurizi** [comment]
@dboyer How does this look?  Note that we won't show diameter (not even "No diameter") if the plot has no tree or if the current user does not have permissions to see diameter.
with-trees

**Comment by steventlamb** [comment]
+1

**Comment by dboyer** [comment]
That looks great.

**Pull request merged**
