### PR TITLE
Fix deprecations prior to upgrading to Django 1.11

### PR DESCRIPTION
**Pull request by maurizi**
Fixes the usage of several deprecated APIs to support upgrading Django to 1.11

Required by https://github.com/OpenTreeMap/otm-addons/pull/1530
Required by https://github.com/OpenTreeMap/otm-cloud/pull/386

Cconnects to https://github.com/OpenTreeMap/otm-core/issues/3157

### CODE REVIEW

**Comment by maurizi** [comment]
@azavea-bot rebuild

**Comment by maurizi** [comment]
I'm investigating the deprecation warnings shown in the CircleCI/TravisCI output now

**Comment by maurizi** [comment]
@azavea-bot rebuild

**Comment by maurizi** [comment]
@azavea-bot rebuild

**Comment by maurizi** [comment]
The UI test failure seems to be a legitimate regression, I'm investigating it now.

**Comment by jwalgran** [comment]
@azavea-bot rebuild

**Pull request merged**
