### PR TITLE
Feature/mw/advanced search style

### PR DESCRIPTION
**Pull request by designmatty**
There is a known issue under the **More** dropdown where the bioswales label falls under the select box. Will need developer for a fix.

### CODE REVIEW

**Comment by RickMohr** [comment]
In "Tree Care", dates are cut off:
image

**Comment by RickMohr** [comment]
(...minor...) In "Tree Care", if you hover over a disabled dropdown the little arrow still lights up.

**Comment by RickMohr** [comment]
More/Bioswales looks OK to me:
image

Do you have an example where it looks bad?

**Comment by RickMohr** [comment]
Otherwise looks awesome!!

**Comment by RickMohr** [comment]
Do we care that the "Advanced" button in its highlighted state is slightly wider, so that hitting "Reset" causes the search boxes to move slightly?

**Comment by designmatty** [comment]
@RickMohr the text "Perennial Plants" is a label for the dropdown above it and the text "Bioswales" acts as a form legend.  "Perennial Plants should be sitting above the dropdown.

**Comment by designmatty** [comment]
It will be easier for me to show the reason why its messed up in person. We can talk when you are back in the office.

**Comment by RickMohr** [comment]
Superseded by #2410

**Pull request closed without merging**
