### PR TITLE
Feature/scalar udf defaults

### PR DESCRIPTION
**Pull request by steventlamb**

### CODE REVIEW

**Comment by maurizi** [comment]
This works well and in general I think the code looks good.

I have reservations about temporarily rolling back our validations on empty choice lists though.  I would rather wait until we get a default list to merge this.

**Comment by steventlamb** [comment]
I agree, and will hold off until @dboyer can provide a set of defaults, or confirm that it's totally impossible.

**Comment by dboyer** [comment]
I'll follow up on getting a default list. I also submitted the question to Mr. Smarty Plants - https://www.wildflower.org/expert/

**Comment by steventlamb** [comment]
closing in favor of #2181, comments addressed there

**Pull request closed without merging**
