### PR TITLE
Translation to catalan

### PR DESCRIPTION
**Pull request by riromu**

### CODE REVIEW

**Comment by azaveaci** [comment]
Can one of the administrators verify this patch?

**Comment by jwalgran** [comment]
Thanks for working on a new OpenTreeMap translation.

There are 2 .po files that need to be created. One for `opentreemap`, which you have already provided, and one for `opentreemap/treemap`, which needs to be added to this PR. This post to the opentreemap-user group explains how to generate the second file using `makemessages`

https://groups.google.com/d/msg/opentreemap-user/5V7aZoP8fPY/B9d2tPorJAAJ

In addition, all contributors to OpenTreeMap must sign a Contributor License Agreement before we can merge their changes. Here is PDF containing the form, along with a description of its purpose and instructions for filling it out and submitting it.

[2016_04_28-OpenTreeMap-Open-Source-Contributor-Agreement-Individual.pdf](https://github.com/OpenTreeMap/otm-core/files/241128/2016_04_28-OpenTreeMap-Open-Source-Contributor-Agreement-Individual.pdf)

**Comment by jwalgran** [comment]
I was mistaken when I suggested that you need to add an additional .po file for `opentreemap/treemap`. All the messages in that file already appear in the `opentreemap` .po file.

We do still require a signed CLA to merge your changes. Thanks.

**Comment by riromu** [comment]
Hello Justin,

I have already sent it.

Regards,

Ricard

2016-04-28 20:36 GMT+02:00 Justin Walgran <notifications@github.com>:

**Comment by jwalgran** [comment]
Thanks for sending us a CLA. Did you send it by email, fax, or postal mail?

**Comment by riromu** [comment]
by mail.
El 02/05/2016 21.48, "Justin Walgran" <notifications@github.com> va
escriure:

**Comment by jwalgran** [comment]
Thank you for your contribution.

**Pull request merged**
