### PR TITLE
Advanced search UI

### PR DESCRIPTION
**Pull request by RickMohr**
* Restructure `instance.advanced_search_fields` and `instance.DEFAULT_SEARCH_FIELDS` to match advanced search categories in UI
* Create partials in new template folder `treemap/partials/advanced_search`
* Add `active` class to dropdowns and "Advanced" button when an advanced search is in effect
* Disable a model's search fields when that model isn't in the display filters
* In stewardship search, disable dropdowns until usable
* Remove CSS for no-longer-used advanced search sliders

Note: Temporarily hard-coding `rainBarrel.capacity` and `bioswale.udf:Perennial Plants` so styling work can proceed

Connects #2372

### CODE REVIEW

**Comment by maurizi** [comment]
If I click into a date search box, then click on something else such as the map, the main search dropdown closes but the date picker window is still present:
floater

**Comment by maurizi** [comment]
If I make `Stewardship` invisible to the current user, the dropdown for `Tree Care` is still present but it has no content.

**Comment by maurizi** [comment]
If I set the permissions for `Planting Site Alerts` to invisible to the current user, I can still choose to search for Planting Sites with open alerts, but the third dropdown is empty.

**Comment by maurizi** [comment]
When I refresh the page, my search terms are correctly applied to the DOM elements for everything except the display filter for planting sites.
This may be caused by https://github.com/OpenTreeMap/otm-core/issues/2379

**Comment by maurizi** [comment]
Code looks good in general.  I think the problems with the date picker and the empty "Tree Care" dropdown should be fixed as part of this PR, but the problem with alerts could be pushed out into another issue.

**Comment by RickMohr** [comment]
@maurizi, ready for another look.

**Comment by maurizi** [comment]
:+1:

**Pull request merged**
