### PR TITLE
Implement Photo review redesign

### PR DESCRIPTION
**Pull request by maurizi**
~~Based on top of https://github.com/OpenTreeMap/otm-core/pull/2334, so commits  8f6bd7b and 799041d are from that PR.~~

 - Redesigns the styling and layout of the photo review page.  The page is now in a table layout instead of a grid layout, matching the comment moderation page.
 - Refactors photo review pagination to work similarly to comment moderation
 - Fixes a few bugs related to photo review, since the code causing them was refactored
 - Records query parameters on comment and photo moderation pages when pagination/filter buttons are clicked.

Connects to OpenTreeMap/otm-addons#541
Connects to OpenTreeMap/otm-addons#828
Connects to #2156

### CODE REVIEW

**Comment by jwalgran** [comment]
Looking at this now

**Comment by maurizi** [comment]
Waffle

**Comment by jwalgran** [comment]
The URL of the "sort" header link is broken

http://localhost:6060/myinstance/photo_review/?&sort=created_at

There are a few things wrong with it:

* `management` is missing from the path
* It should be `photo-review` not `photo_review`
* `?&` in front of the query argument is probably ok, but looks a little odd.

**Comment by jwalgran** [comment]
If you rotate a previously approved photo and it will get stuck in the management UI

1. On the tree detail page add a photo
2. On the management page approve the photo
3. On the tree detail page, rotate the photo

The rotated photo will appear on the management page, but clicking "Approve" or "Reject" generates a 500

```
Internal Server Error: /myinstance/features/1110498/photo/8030/approve
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/app/core/opentreemap/treemap/decorators.py", line 45, in wrapper
    return view_fn(request, instance, *args, **kwargs)
  File "/opt/app/core/opentreemap/treemap/decorators.py", line 69, in f
    return view_fn(request, instance, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 79, in wrapper
    params = callable_or_dict(request, *args, **wrapper_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/app/core/opentreemap/treemap/views/photo.py", line 112, in approve_or_reject_photo
    audit, request.user, approved)
  File "/opt/app/core/opentreemap/treemap/audit.py", line 221, in approve_or_reject_existing_edit
    raise Exception('This audit has already been approved or rejected')
```

I would be ok to push the handling of this edge case into a separate issue.

**Comment by jwalgran** [comment]
I would like to style the "DATE" column header as a link. Right now there is no visual indication to the user that this cool sorting feature is available.

screen shot 2015-11-04 at 4 20 04 pm

**Comment by jwalgran** [comment]
+1

**Pull request merged**
