### PR TITLE
Backfill canopy_boundary_category column before making non null

### PR DESCRIPTION
**Pull request by kdeloach**
Fixes an error received applying migrations to staging.

Ref: OpenTreeMap/otm-cloud#234

### CODE REVIEW

**Comment by jwalgran** [comment]
What is the best way to recreate the problem in my dev database?

**Comment by kdeloach** [comment]
For reasons not entirely clear to me, I was not able to run migrations against the production database backup without these changes.

**Comment by kdeloach** [comment]
I could only reproduce this error by running migrations against a production database backup. It's possible that restoring from a backup causes this error, and that this is not necessary at all. It still might be a good idea to include this just to be on the safe side.

**Comment by kdeloach** [comment]
I also found that doing a reverse migration to drop the canopy columns and then re-running migrations also fixes this problem... Which is another indication that the backup I restored from may have been dumped in a weird state.

**Comment by jwalgran** [comment]
Migrations applied cleanly. After this migration, my `canopy_boundary_category` does not have nulls.

```
select url_name, canopy_boundary_category from treemap_instance where canopy_boundary_category is null;
 url_name | canopy_boundary_category
----------+--------------------------
```
👍

**Pull request merged**
