### PR TITLE
Feature/unify csv columns

### PR DESCRIPTION
**Pull request by steventlamb**
Connects #2504 
Connects #2505

### CODE REVIEW

**Comment by steventlamb** [comment]
This has at least one known outstanding issue:
- `tree__plot` is the only export field that was observed to reliably contains a plot ID, so it was promoted to the primary plot ID field. This doesn't work for plots that don't have trees. This must be fixed.

it probably also has the following:
- will not work for instances with alerts

it's been suggested to add the following:
- add unit tests that exports and then imports

**Comment by RickMohr** [comment]
waffle

**Comment by RickMohr** [comment]
waffle

**Comment by RickMohr** [comment]
closing in favor of #2533

**Pull request closed without merging**
