### PR TITLE
Update styling for modeling UI update

### PR DESCRIPTION
**Pull request by kdeloach**

### CODE REVIEW

**Comment by RickMohr** [comment]
@kdeloach, does this need some CSS tweaks committed?

**Comment by kdeloach** [comment]
I forgot to push the latest changes up. Thanks for catching that.

**Comment by RickMohr** [comment]
Looks like there's some lint:

cloud_management/instance.py:13:1: F401 'Point' imported but unused

**Comment by RickMohr** [comment]
+1

**Pull request merged**
