### PR TITLE
Create django.po

### PR DESCRIPTION
**Pull request by nicoali**
Translation in italian.
Maybe i've to change something. Because i've transleted from poedit but when i'll see on the website something can be change.

### CODE REVIEW

**Comment by azaveaci** [comment]
Can one of the administrators verify this patch?

**Comment by jwalgran** [comment]
Thank you for submitting this translation.

All contributors to OpenTreeMap must sign a Contributor License Agreement before we can merge their changes. Here is PDF containing the form, along with a description of its purpose and instructions for filling it out and submitting it.

[2016_04_28-OpenTreeMap-Open-Source-Contributor-Agreement-Individual.pdf](https://github.com/OpenTreeMap/otm-core/files/240990/2016_04_28-OpenTreeMap-Open-Source-Contributor-Agreement-Individual.pdf)

**Comment by nicoali** [comment]
i'll sign and send it as soon as possible.
I cannot print until Monday :)

**Comment by nicoali** [comment]
I siged and sent the contributor licensr agreement to cla@azavea.com
i recieved an automatic reply email that he was out of office.

Did you recieved it?

**Comment by rcheetham** [comment]
I'm sorry for not sending confirmation. I received the CLA.

**Comment by jwalgran** [comment]
Jenkins, ok to test.

**Comment by jwalgran** [comment]
Thank you for your contribution.

**Comment by nicoali** [comment]
Not at all! Thank you to the staff that always support me when i've a
problem

I've also changed all the common names of species trees in italian. If
someone need it i'll commit.

2016-06-09 19:25 GMT+02:00 Justin Walgran <notifications@github.com>:

**Pull request merged**
