### PR TITLE
Fix saving models when collection UDFs are not writable.

### PR DESCRIPTION
**Pull request by maurizi**
Setting collection UDFs to read-only would prevent editing a model if
that model already had collection UDF data on it.  The fix is rather
simple - we no longer attempt to save collection UDF data if there have
been no changes.

I also fixed an issue with clean_value for collection UDFs where it would
attempt to parse a datetime object as a formatted string and turn it into
a date.  This was mostly a symptom, not a cause of the underlying issue,
but it is more correct anyways.

### CODE REVIEW

**Comment by steventlamb** [comment]
please link this commit message to the issue it fixes

**Comment by steventlamb** [comment]
Needs a fix for instances that have multiple udfs per model

**Comment by maurizi** [comment]
@steventlamb Code fixed, unit tests pass.

**Comment by steventlamb** [comment]
+1

**Pull request merged**
