### PR TITLE
Fix UI tests

### PR DESCRIPTION
**Pull request by maurizi**
A couple of small changes here:
 - A code cleanup to remove a monkey patch that is no longer needed
 - Some changes to test setup to fix regressions introduced by the switch to Webpack
 - A fix to a UI test that seems to have started failing due to timing issues

Connects to OpenTreeMap/otm-cloud#258

### CODE REVIEW

**Comment by RobinIsTheBird** [comment]
Waiting for all the ui tests to run before I give it the +1. So far, looks headed for +1.

**Comment by RobinIsTheBird** [comment]
I'm going to give this a :+1: even though that one test still fails, because it's so much better than before.

Would it make sense to open a separate issue for the straggler?

**Comment by maurizi** [comment]
> I'm going to give this a :+1: even though that one test still fails, because it's so much better than before.

> Would it make sense to open a separate issue for the straggler?

I want to get that last test working as well. I suspect adding some waiting is all it will need.

I'll re-assign this to you when I have the last test fixed.

**Comment by RobinIsTheBird** [comment]
:+1:

**Pull request merged**
