### PR TITLE
clean up the suspend map page

### PR DESCRIPTION
**Pull request by designmatty**
connected to https://github.com/OpenTreeMap/otm-addons/pull/875

### CODE REVIEW

**Comment by designmatty** [comment]
This fixes the margin-top of the alerts across all management pages.

**Comment by RickMohr** [comment]
Do you know if other uses of `.alert` on management pages continue to look good with this change?

**Comment by designmatty** [comment]
I checked on 3-4 other management pages including those that have 2 alerts in a row and they all looked fine. The margin was added months ago when Christopher first did his work so I assume the reason for the margin no longer exists.

**Comment by RickMohr** [comment]
+1 thanks for checking out the other uses.

**Pull request merged**
