### PR TITLE
Upgrade to Django 1.8

### PR DESCRIPTION
**Pull request by maurizi**
There is a lot going on here, there is a more detailed summary of changes in the individual commits.

In brief this:
 - Fixes some usage of deprecated features that were completely removed in django 1.8
 - Updates several of our plugins to work with django 1.8
 - Switches from South to Django migrations
 - Fixes a number of places that were using internal Django APIs, most notably UDFs

To upgrade a Django 1.6 environment to Django 1.8, you must run the following steps:
 - Checkout the latest version of the master branch, and run all migrations
 - Checkout this branch
 - Delete all `.pyc` files. (`find -name '*.pyc' -delete`)
 - Reprovision to update python dependencies
 - Run core django migrations with: `python manage.py migrate --fake-initial auth`
 - Run django comment migrations with: `python manage.py migrate --fake-initial django_comments`
 - Run OTM migrations with: `python manage.py migrate --fake`

Some things to test:
 - That the above steps work to upgrade an existing Django 1.6 environment
 - That it is possible to provision a new development environment and run migrations using this branch
 - That all of the various features of the site still work.

### CODE REVIEW

**Comment by maurizi** [comment]
It looks like there were some git rebase issues, I'll reassign once they're fixed.

**Comment by maurizi** [comment]
Looks like there is an issue with Django Registration (I was unable to register a new user), which I am looking into

**Comment by steventlamb** [comment]
Broken unit tests, after the registration fixup:
```
(env)vagrant@precise64:/usr/local/otm/app/opentreemap$ python manage.py test
start: Job is already running: ecoservice
start: Job is already running: ecoservice
Creating test database for alias 'default'...
Installed 16 object(s) from 1 fixture(s)
Installed 5 object(s) from 1 fixture(s)
Installed 18 object(s) from 1 fixture(s)
....s.s....................s.ss............s.s..s.ss...s...s.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s...........................................................s.....................EEEEE...............................................................................................ssssssssssssss..........s....................................................................................................
======================================================================
ERROR: test_adds_to_invited_instances_after_activation (cloud_management.tests.InstanceInvitationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/otm/app/opentreemap/cloud_management/tests.py", line 2001, in test_adds_to_invited_instances_after_activation
    "different@other.com")
  File "/usr/local/otm/app/opentreemap/cloud_management/tests.py", line 1922, in _invite_and_register
    password1="pass")
TypeError: register() got an unexpected keyword argument 'email'

======================================================================
ERROR: test_adds_to_invited_instances_and_redirects (cloud_management.tests.InstanceInvitationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/otm/app/opentreemap/cloud_management/tests.py", line 1943, in test_adds_to_invited_instances_and_redirects
    request, rv = self._invite_and_register("some@email.com")
  File "/usr/local/otm/app/opentreemap/cloud_management/tests.py", line 1922, in _invite_and_register
    password1="pass")
TypeError: register() got an unexpected keyword argument 'email'

======================================================================
ERROR: test_does_not_redirect_when_email_different (cloud_management.tests.InstanceInvitationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/otm/app/opentreemap/cloud_management/tests.py", line 1953, in test_does_not_redirect_when_email_different
    "different@other.com")
  File "/usr/local/otm/app/opentreemap/cloud_management/tests.py", line 1922, in _invite_and_register
    password1="pass")
TypeError: register() got an unexpected keyword argument 'email'

======================================================================
ERROR: test_does_not_redirect_when_key_does_not_match (cloud_management.tests.InstanceInvitationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/otm/app/opentreemap/cloud_management/tests.py", line 1977, in test_does_not_redirect_when_key_does_not_match
    key_matches=False)
  File "/usr/local/otm/app/opentreemap/cloud_management/tests.py", line 1922, in _invite_and_register
    password1="pass")
TypeError: register() got an unexpected keyword argument 'email'

======================================================================
ERROR: test_normal_registration_without_invite (cloud_management.tests.InstanceInvitationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/otm/app/opentreemap/cloud_management/tests.py", line 1878, in test_normal_registration_without_invite
    password1="pass")
TypeError: register() got an unexpected keyword argument 'email'

----------------------------------------------------------------------
Ran 912 tests in 309.006s

FAILED (errors=5, skipped=29)
Destroying test database for alias 'default'...
(env)vagrant@precise64:/usr/local/otm/app/opentreemap$ 

```

**Comment by steventlamb** [comment]
lingering inconsistency, probably due to things that south didn't track but django does, like choices:
```
(env)vagrant@precise64:/usr/local/otm/app/opentreemap$ python manage.py migrate --fake-initial contenttypes
System check identified some issues:

WARNINGS:
treemap.Instance.boundaries: (fields.W340) null has no effect on ManyToManyField.
treemap.Instance.users: (fields.W340) null has no effect on ManyToManyField.
Operations to perform:
  Apply all migrations: contenttypes
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

```

**Comment by steventlamb** [comment]
+ 0.75. This is coming along - the app runs and the unit tests mostly pass. I'll keep exercising it as I'll use it as the base for stuff I work on in the next few days.

**Comment by maurizi** [comment]
@steventlamb I rebuilt the initial migrations for the `exporter` app, which should fix the "Your models have changes that are not yet reflected in a migration" (but will probably make Django unhappy, since you've applied migrations that no longer exist).
I'll look into the test failures tomorrow.

**Comment by steventlamb** [comment]
migrations and new instructions work great.

**Comment by RickMohr** [comment]
Testing this now.

**Comment by RickMohr** [comment]
For me, `runserver` gives these warnings:
```
WARNINGS:
treemap.Instance.boundaries: (fields.W340) null has no effect on ManyToManyField.
treemap.Instance.users: (fields.W340) null has no effect on ManyToManyField.
```

**Comment by maurizi** [comment]
@RickMohr I've written an issue to cover fixing those.  It should be simple enough to fix these, but I'd like to avoid making any "real" schema migrations until after this update gets pushed to production if at all possible.

**Comment by RickMohr** [comment]
+1 I tested many aspects of user registration, management pages, custom fields, search, and tree/plot editing. Looks good!!

**Pull request merged**
